"""Comprehensive institutional asset universe covering Nifty 50, Bonds, REITs, ETFs, FDs, Savings, Commodities, and Crypto."""

from typing import Any

CURATED_ASSETS: list[dict[str, Any]] = [
    # ── Benchmark Indices ───────────────────────────────────────────────────────
    {
        "ticker": "^NSEI",
        "name": "Nifty 50 Index",
        "asset_class": "equity",
        "sector": "Broad Market",
        "category": "indian_index",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.135,
        "annual_volatility": 0.16,
        "equity_corr": 1.0,
    },
    {
        "ticker": "^NSEBANK",
        "name": "Nifty Bank Index",
        "asset_class": "equity",
        "sector": "Financial Services",
        "category": "indian_index",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.142,
        "annual_volatility": 0.21,
        "equity_corr": 0.88,
    },
    {
        "ticker": "^CNXIT",
        "name": "Nifty IT Index",
        "asset_class": "equity",
        "sector": "Technology",
        "category": "indian_index",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.155,
        "annual_volatility": 0.22,
        "equity_corr": 0.72,
    },
    # ── Nifty 50 Indian Equities (All 50 Major Companies) ───────────────────────
    {
        "ticker": "RELIANCE.NS",
        "name": "Reliance Industries Ltd",
        "asset_class": "equity",
        "sector": "Energy",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.165,
        "annual_volatility": 0.21,
        "equity_corr": 0.75,
    },
    {
        "ticker": "TCS.NS",
        "name": "Tata Consultancy Services Ltd",
        "asset_class": "equity",
        "sector": "Technology",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.148,
        "annual_volatility": 0.19,
        "equity_corr": 0.65,
    },
    {
        "ticker": "HDFCBANK.NS",
        "name": "HDFC Bank Ltd",
        "asset_class": "equity",
        "sector": "Financial Services",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.152,
        "annual_volatility": 0.20,
        "equity_corr": 0.78,
    },
    {
        "ticker": "INFY.NS",
        "name": "Infosys Ltd",
        "asset_class": "equity",
        "sector": "Technology",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.151,
        "annual_volatility": 0.22,
        "equity_corr": 0.68,
    },
    {
        "ticker": "ICICIBANK.NS",
        "name": "ICICI Bank Ltd",
        "asset_class": "equity",
        "sector": "Financial Services",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.175,
        "annual_volatility": 0.23,
        "equity_corr": 0.80,
    },
    {
        "ticker": "HINDUNILVR.NS",
        "name": "Hindustan Unilever Ltd",
        "asset_class": "equity",
        "sector": "Consumer Defensive",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.125,
        "annual_volatility": 0.15,
        "equity_corr": 0.45,
    },
    {
        "ticker": "ITC.NS",
        "name": "ITC Ltd",
        "asset_class": "equity",
        "sector": "Consumer Defensive",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.140,
        "annual_volatility": 0.18,
        "equity_corr": 0.50,
    },
    {
        "ticker": "SBIN.NS",
        "name": "State Bank of India",
        "asset_class": "equity",
        "sector": "Financial Services",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.168,
        "annual_volatility": 0.25,
        "equity_corr": 0.82,
    },
    {
        "ticker": "BHARTIARTL.NS",
        "name": "Bharti Airtel Ltd",
        "asset_class": "equity",
        "sector": "Communication Services",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.185,
        "annual_volatility": 0.21,
        "equity_corr": 0.62,
    },
    {
        "ticker": "LICI.NS",
        "name": "Life Insurance Corp of India",
        "asset_class": "equity",
        "sector": "Financial Services",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.130,
        "annual_volatility": 0.22,
        "equity_corr": 0.60,
    },
    {
        "ticker": "KOTAKBANK.NS",
        "name": "Kotak Mahindra Bank Ltd",
        "asset_class": "equity",
        "sector": "Financial Services",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.138,
        "annual_volatility": 0.19,
        "equity_corr": 0.72,
    },
    {
        "ticker": "LT.NS",
        "name": "Larsen & Toubro Ltd",
        "asset_class": "equity",
        "sector": "Industrials",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.172,
        "annual_volatility": 0.21,
        "equity_corr": 0.74,
    },
    {
        "ticker": "AXISBANK.NS",
        "name": "Axis Bank Ltd",
        "asset_class": "equity",
        "sector": "Financial Services",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.158,
        "annual_volatility": 0.24,
        "equity_corr": 0.79,
    },
    {
        "ticker": "HCLTECH.NS",
        "name": "HCL Technologies Ltd",
        "asset_class": "equity",
        "sector": "Technology",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.156,
        "annual_volatility": 0.20,
        "equity_corr": 0.64,
    },
    {
        "ticker": "BAJFINANCE.NS",
        "name": "Bajaj Finance Ltd",
        "asset_class": "equity",
        "sector": "Financial Services",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.190,
        "annual_volatility": 0.28,
        "equity_corr": 0.76,
    },
    {
        "ticker": "MARUTI.NS",
        "name": "Maruti Suzuki India Ltd",
        "asset_class": "equity",
        "sector": "Consumer Cyclical",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.145,
        "annual_volatility": 0.21,
        "equity_corr": 0.66,
    },
    {
        "ticker": "SUNPHARMA.NS",
        "name": "Sun Pharmaceutical Industries",
        "asset_class": "equity",
        "sector": "Healthcare",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.162,
        "annual_volatility": 0.18,
        "equity_corr": 0.48,
    },
    {
        "ticker": "TITAN.NS",
        "name": "Titan Company Ltd",
        "asset_class": "equity",
        "sector": "Consumer Cyclical",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.180,
        "annual_volatility": 0.23,
        "equity_corr": 0.68,
    },
    {
        "ticker": "ULTRACEMCO.NS",
        "name": "UltraTech Cement Ltd",
        "asset_class": "equity",
        "sector": "Basic Materials",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.154,
        "annual_volatility": 0.20,
        "equity_corr": 0.69,
    },
    {
        "ticker": "ASIANPAINT.NS",
        "name": "Asian Paints Ltd",
        "asset_class": "equity",
        "sector": "Consumer Cyclical",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.132,
        "annual_volatility": 0.19,
        "equity_corr": 0.58,
    },
    {
        "ticker": "TATAMOTORS.NS",
        "name": "Tata Motors Ltd",
        "asset_class": "equity",
        "sector": "Consumer Cyclical",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.210,
        "annual_volatility": 0.32,
        "equity_corr": 0.73,
    },
    {
        "ticker": "NTPC.NS",
        "name": "NTPC Ltd",
        "asset_class": "equity",
        "sector": "Utilities",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.165,
        "annual_volatility": 0.20,
        "equity_corr": 0.62,
    },
    {
        "ticker": "ONGC.NS",
        "name": "Oil & Natural Gas Corp",
        "asset_class": "equity",
        "sector": "Energy",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.148,
        "annual_volatility": 0.24,
        "equity_corr": 0.64,
    },
    {
        "ticker": "POWERGRID.NS",
        "name": "Power Grid Corp of India",
        "asset_class": "equity",
        "sector": "Utilities",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.152,
        "annual_volatility": 0.17,
        "equity_corr": 0.55,
    },
    {
        "ticker": "TATASTEEL.NS",
        "name": "Tata Steel Ltd",
        "asset_class": "equity",
        "sector": "Basic Materials",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.170,
        "annual_volatility": 0.30,
        "equity_corr": 0.76,
    },
    {
        "ticker": "M&M.NS",
        "name": "Mahindra & Mahindra Ltd",
        "asset_class": "equity",
        "sector": "Consumer Cyclical",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.205,
        "annual_volatility": 0.25,
        "equity_corr": 0.71,
    },
    {
        "ticker": "COALINDIA.NS",
        "name": "Coal India Ltd",
        "asset_class": "equity",
        "sector": "Energy",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.160,
        "annual_volatility": 0.23,
        "equity_corr": 0.58,
    },
    {
        "ticker": "BAJAJFINSV.NS",
        "name": "Bajaj Finserv Ltd",
        "asset_class": "equity",
        "sector": "Financial Services",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.162,
        "annual_volatility": 0.26,
        "equity_corr": 0.75,
    },
    {
        "ticker": "ADANIENT.NS",
        "name": "Adani Enterprises Ltd",
        "asset_class": "equity",
        "sector": "Industrials",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.220,
        "annual_volatility": 0.38,
        "equity_corr": 0.68,
    },
    {
        "ticker": "ADANIPORTS.NS",
        "name": "Adani Ports & SEZ Ltd",
        "asset_class": "equity",
        "sector": "Industrials",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.178,
        "annual_volatility": 0.27,
        "equity_corr": 0.70,
    },
    {
        "ticker": "JSWSTEEL.NS",
        "name": "JSW Steel Ltd",
        "asset_class": "equity",
        "sector": "Basic Materials",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.164,
        "annual_volatility": 0.29,
        "equity_corr": 0.74,
    },
    {
        "ticker": "HINDALCO.NS",
        "name": "Hindalco Industries Ltd",
        "asset_class": "equity",
        "sector": "Basic Materials",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.175,
        "annual_volatility": 0.30,
        "equity_corr": 0.73,
    },
    {
        "ticker": "GRASIM.NS",
        "name": "Grasim Industries Ltd",
        "asset_class": "equity",
        "sector": "Basic Materials",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.155,
        "annual_volatility": 0.22,
        "equity_corr": 0.69,
    },
    {
        "ticker": "TECHM.NS",
        "name": "Tech Mahindra Ltd",
        "asset_class": "equity",
        "sector": "Technology",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.142,
        "annual_volatility": 0.24,
        "equity_corr": 0.65,
    },
    {
        "ticker": "WIPRO.NS",
        "name": "Wipro Ltd",
        "asset_class": "equity",
        "sector": "Technology",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.128,
        "annual_volatility": 0.22,
        "equity_corr": 0.63,
    },
    {
        "ticker": "CIPLA.NS",
        "name": "Cipla Ltd",
        "asset_class": "equity",
        "sector": "Healthcare",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.148,
        "annual_volatility": 0.19,
        "equity_corr": 0.44,
    },
    {
        "ticker": "NESTLEIND.NS",
        "name": "Nestle India Ltd",
        "asset_class": "equity",
        "sector": "Consumer Defensive",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.135,
        "annual_volatility": 0.16,
        "equity_corr": 0.42,
    },
    {
        "ticker": "DRREDDY.NS",
        "name": "Dr Reddy's Laboratories",
        "asset_class": "equity",
        "sector": "Healthcare",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.146,
        "annual_volatility": 0.20,
        "equity_corr": 0.46,
    },
    {
        "ticker": "SBILIFE.NS",
        "name": "SBI Life Insurance Co Ltd",
        "asset_class": "equity",
        "sector": "Financial Services",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.150,
        "annual_volatility": 0.21,
        "equity_corr": 0.67,
    },
    {
        "ticker": "BPCL.NS",
        "name": "Bharat Petroleum Corp Ltd",
        "asset_class": "equity",
        "sector": "Energy",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.144,
        "annual_volatility": 0.25,
        "equity_corr": 0.61,
    },
    {
        "ticker": "BRITANNIA.NS",
        "name": "Britannia Industries Ltd",
        "asset_class": "equity",
        "sector": "Consumer Defensive",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.138,
        "annual_volatility": 0.17,
        "equity_corr": 0.46,
    },
    {
        "ticker": "TATACONSUM.NS",
        "name": "Tata Consumer Products Ltd",
        "asset_class": "equity",
        "sector": "Consumer Defensive",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.152,
        "annual_volatility": 0.20,
        "equity_corr": 0.52,
    },
    {
        "ticker": "EICHERMOT.NS",
        "name": "Eicher Motors Ltd",
        "asset_class": "equity",
        "sector": "Consumer Cyclical",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.165,
        "annual_volatility": 0.23,
        "equity_corr": 0.66,
    },
    {
        "ticker": "APOLLOHOSP.NS",
        "name": "Apollo Hospitals Enterprise",
        "asset_class": "equity",
        "sector": "Healthcare",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.182,
        "annual_volatility": 0.24,
        "equity_corr": 0.53,
    },
    {
        "ticker": "DIVISLAB.NS",
        "name": "Divi's Laboratories Ltd",
        "asset_class": "equity",
        "sector": "Healthcare",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.158,
        "annual_volatility": 0.25,
        "equity_corr": 0.49,
    },
    {
        "ticker": "HEROMOTOCO.NS",
        "name": "Hero MotoCorp Ltd",
        "asset_class": "equity",
        "sector": "Consumer Cyclical",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.142,
        "annual_volatility": 0.22,
        "equity_corr": 0.63,
    },
    {
        "ticker": "SHREECEM.NS",
        "name": "Shree Cement Ltd",
        "asset_class": "equity",
        "sector": "Basic Materials",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.136,
        "annual_volatility": 0.22,
        "equity_corr": 0.65,
    },
    {
        "ticker": "BAJAJ-AUTO.NS",
        "name": "Bajaj Auto Ltd",
        "asset_class": "equity",
        "sector": "Consumer Cyclical",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.170,
        "annual_volatility": 0.21,
        "equity_corr": 0.64,
    },
    {
        "ticker": "INDUSINDBK.NS",
        "name": "IndusInd Bank Ltd",
        "asset_class": "equity",
        "sector": "Financial Services",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.154,
        "annual_volatility": 0.28,
        "equity_corr": 0.77,
    },
    {
        "ticker": "UPL.NS",
        "name": "UPL Ltd",
        "asset_class": "equity",
        "sector": "Basic Materials",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.120,
        "annual_volatility": 0.31,
        "equity_corr": 0.62,
    },
    # ── Fixed Deposits & Liquid Savings (Cash & Debt) ───────────────────────────
    {
        "ticker": "SBI_FD",
        "name": "SBI 1-Yr Fixed Deposit (6.8%)",
        "asset_class": "debt",
        "sector": "Fixed Income / Cash",
        "category": "synthetic",
        "currency": "INR",
        "is_synthetic": True,
        "annual_return": 0.068,
        "annual_volatility": 0.001,
        "equity_corr": 0.0,
        "assumption_notes": "Constant daily compounding yield accrual at 6.8% p.a.",
    },
    {
        "ticker": "HDFC_FD",
        "name": "HDFC Bank 1-Yr Fixed Deposit (7.1%)",
        "asset_class": "debt",
        "sector": "Fixed Income / Cash",
        "category": "synthetic",
        "currency": "INR",
        "is_synthetic": True,
        "annual_return": 0.071,
        "annual_volatility": 0.001,
        "equity_corr": 0.0,
        "assumption_notes": "Constant daily compounding yield accrual at 7.1% p.a.",
    },
    {
        "ticker": "SAVINGS_ACCOUNT",
        "name": "High-Yield Liquid Savings Account (4.0%)",
        "asset_class": "debt",
        "sector": "Cash & Equivalents",
        "category": "synthetic",
        "currency": "INR",
        "is_synthetic": True,
        "annual_return": 0.040,
        "annual_volatility": 0.0005,
        "equity_corr": 0.0,
        "assumption_notes": "Zero credit risk, daily liquidity cash buffer.",
    },
    {
        "ticker": "TREASURY_BILL_91D",
        "name": "RBI 91-Day Treasury Bill (6.7%)",
        "asset_class": "debt",
        "sector": "Sovereign Short-Term",
        "category": "synthetic",
        "currency": "INR",
        "is_synthetic": True,
        "annual_return": 0.067,
        "annual_volatility": 0.008,
        "equity_corr": -0.05,
        "assumption_notes": "Ultra-short sovereign debt instrument.",
    },
    # ── Sovereign & Corporate Bonds (Debt) ──────────────────────────────────────
    {
        "ticker": "INDIA_GOVT_10Y",
        "name": "Govt of India 10Y Benchmark Sovereign Bond (7.15%)",
        "asset_class": "debt",
        "sector": "Sovereign Debt",
        "category": "synthetic",
        "currency": "INR",
        "is_synthetic": True,
        "annual_return": 0.0715,
        "annual_volatility": 0.035,
        "equity_corr": -0.12,
        "assumption_notes": "Deterministic yield model with duration ~6.8 sensitivity.",
    },
    {
        "ticker": "INDIA_CORP_AAA",
        "name": "CRISIL AAA Corporate Bond Benchmark (7.9%)",
        "asset_class": "debt",
        "sector": "Corporate Debt",
        "category": "synthetic",
        "currency": "INR",
        "is_synthetic": True,
        "annual_return": 0.079,
        "annual_volatility": 0.040,
        "equity_corr": -0.08,
        "assumption_notes": "High quality institutional corporate paper.",
    },
    {
        "ticker": "US_TREASURY_10Y",
        "name": "US 10-Year Treasury Benchmark (4.3%)",
        "asset_class": "debt",
        "sector": "Global Sovereign Debt",
        "category": "synthetic",
        "currency": "USD",
        "is_synthetic": True,
        "annual_return": 0.043,
        "annual_volatility": 0.065,
        "equity_corr": -0.20,
        "assumption_notes": "Global risk-free anchor in USD.",
    },
    {
        "ticker": "BND",
        "name": "Vanguard Total Bond Market ETF",
        "asset_class": "debt",
        "sector": "Global Fixed Income",
        "category": "us_etf",
        "currency": "USD",
        "is_synthetic": False,
        "annual_return": 0.048,
        "annual_volatility": 0.058,
        "equity_corr": -0.15,
    },
    # ── Real Estate Investment Trusts (REITs) ───────────────────────────────────
    {
        "ticker": "EMBASSY_REIT",
        "name": "Embassy Office Parks REIT",
        "asset_class": "alternative",
        "sector": "Real Estate",
        "category": "reit",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.092,
        "annual_volatility": 0.135,
        "equity_corr": 0.42,
    },
    {
        "ticker": "MINDSPACE_REIT",
        "name": "Mindspace Business Parks REIT",
        "asset_class": "alternative",
        "sector": "Real Estate",
        "category": "reit",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.090,
        "annual_volatility": 0.130,
        "equity_corr": 0.40,
    },
    {
        "ticker": "BROOKFIELD_REIT",
        "name": "Brookfield India Real Estate Trust",
        "asset_class": "alternative",
        "sector": "Real Estate",
        "category": "reit",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.095,
        "annual_volatility": 0.145,
        "equity_corr": 0.45,
    },
    {
        "ticker": "VNQ",
        "name": "Vanguard Real Estate US ETF",
        "asset_class": "alternative",
        "sector": "Global Real Estate",
        "category": "us_etf",
        "currency": "USD",
        "is_synthetic": False,
        "annual_return": 0.088,
        "annual_volatility": 0.175,
        "equity_corr": 0.55,
    },
    # ── Commodities (Gold, Silver, Energy, Metals) ──────────────────────────────
    {
        "ticker": "GOLDBEES.NS",
        "name": "Nippon India ETF Gold BeES",
        "asset_class": "commodity",
        "sector": "Precious Metals",
        "category": "commodity_etf",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.115,
        "annual_volatility": 0.130,
        "equity_corr": -0.05,
    },
    {
        "ticker": "SILVERBEES.NS",
        "name": "Nippon India ETF Silver BeES",
        "asset_class": "commodity",
        "sector": "Precious Metals",
        "category": "commodity_etf",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.128,
        "annual_volatility": 0.240,
        "equity_corr": 0.15,
    },
    {
        "ticker": "CRUDE_OIL",
        "name": "WTI / MCX Crude Oil Commodity Benchmark",
        "asset_class": "commodity",
        "sector": "Energy Commodities",
        "category": "commodity_synthetic",
        "currency": "USD",
        "is_synthetic": True,
        "annual_return": 0.075,
        "annual_volatility": 0.320,
        "equity_corr": 0.25,
    },
    {
        "ticker": "COPPER",
        "name": "Global Copper & Industrial Metals Fund",
        "asset_class": "commodity",
        "sector": "Industrial Metals",
        "category": "commodity_synthetic",
        "currency": "USD",
        "is_synthetic": True,
        "annual_return": 0.085,
        "annual_volatility": 0.220,
        "equity_corr": 0.35,
    },
    # ── Global & US ETFs ────────────────────────────────────────────────────────
    {
        "ticker": "SPY",
        "name": "SPDR S&P 500 ETF Trust",
        "asset_class": "equity",
        "sector": "US Broad Market",
        "category": "us_etf",
        "currency": "USD",
        "is_synthetic": False,
        "annual_return": 0.125,
        "annual_volatility": 0.155,
        "equity_corr": 0.65,
    },
    {
        "ticker": "QQQ",
        "name": "Invesco QQQ Trust Nasdaq 100",
        "asset_class": "equity",
        "sector": "US Technology",
        "category": "us_etf",
        "currency": "USD",
        "is_synthetic": False,
        "annual_return": 0.165,
        "annual_volatility": 0.210,
        "equity_corr": 0.68,
    },
    {
        "ticker": "VTI",
        "name": "Vanguard Total Stock Market ETF",
        "asset_class": "equity",
        "sector": "US Broad Market",
        "category": "us_etf",
        "currency": "USD",
        "is_synthetic": False,
        "annual_return": 0.122,
        "annual_volatility": 0.158,
        "equity_corr": 0.66,
    },
    {
        "ticker": "VT",
        "name": "Vanguard Total World Stock ETF",
        "asset_class": "equity",
        "sector": "Global Broad Market",
        "category": "us_etf",
        "currency": "USD",
        "is_synthetic": False,
        "annual_return": 0.110,
        "annual_volatility": 0.150,
        "equity_corr": 0.70,
    },
    {
        "ticker": "EEM",
        "name": "iShares MSCI Emerging Markets ETF",
        "asset_class": "equity",
        "sector": "Emerging Markets",
        "category": "us_etf",
        "currency": "USD",
        "is_synthetic": False,
        "annual_return": 0.095,
        "annual_volatility": 0.190,
        "equity_corr": 0.60,
    },
    # ── Cryptocurrencies & Digital Assets ───────────────────────────────────────
    {
        "ticker": "BTC-USD",
        "name": "Bitcoin (Digital Reserve Asset)",
        "asset_class": "alternative",
        "sector": "Cryptocurrency",
        "category": "crypto",
        "currency": "USD",
        "is_synthetic": False,
        "annual_return": 0.350,
        "annual_volatility": 0.550,
        "equity_corr": 0.28,
    },
    {
        "ticker": "ETH-USD",
        "name": "Ethereum (Smart Contract Protocol)",
        "asset_class": "alternative",
        "sector": "Cryptocurrency",
        "category": "crypto",
        "currency": "USD",
        "is_synthetic": False,
        "annual_return": 0.320,
        "annual_volatility": 0.620,
        "equity_corr": 0.30,
    },
    {
        "ticker": "SOL-USD",
        "name": "Solana (Decentralized Finance)",
        "asset_class": "alternative",
        "sector": "Cryptocurrency",
        "category": "crypto",
        "currency": "USD",
        "is_synthetic": False,
        "annual_return": 0.380,
        "annual_volatility": 0.720,
        "equity_corr": 0.26,
    },
]
