"""Curated asset universe with classification and synthetic modeling assumptions."""

from typing import Any

CURATED_ASSETS: list[dict[str, Any]] = [
    # ── Indian Large Cap Equities ─────────────────────────────────────────────
    {
        "ticker": "^NSEI",
        "name": "Nifty 50 Index",
        "asset_class": "equity",
        "sector": "Broad Market",
        "category": "indian_index",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.135,
        "annual_volatility": 0.16,
        "equity_corr": 1.0,
    },
    {
        "ticker": "^NSEBANK",
        "name": "Nifty Bank Index",
        "asset_class": "equity",
        "sector": "Finance",
        "category": "indian_index",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.142,
        "annual_volatility": 0.21,
        "equity_corr": 0.88,
    },
    {
        "ticker": "^CNXIT",
        "name": "Nifty IT Index",
        "asset_class": "equity",
        "sector": "Technology",
        "category": "indian_index",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.155,
        "annual_volatility": 0.22,
        "equity_corr": 0.72,
    },
    {
        "ticker": "RELIANCE.NS",
        "name": "Reliance Industries Ltd",
        "asset_class": "equity",
        "sector": "Energy",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.165,
        "annual_volatility": 0.21,
        "equity_corr": 0.75,
    },
    {
        "ticker": "TCS.NS",
        "name": "Tata Consultancy Services Ltd",
        "asset_class": "equity",
        "sector": "Technology",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.145,
        "annual_volatility": 0.19,
        "equity_corr": 0.65,
    },
    {
        "ticker": "HDFCBANK.NS",
        "name": "HDFC Bank Ltd",
        "asset_class": "equity",
        "sector": "Finance",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.138,
        "annual_volatility": 0.20,
        "equity_corr": 0.78,
    },
    {
        "ticker": "INFY.NS",
        "name": "Infosys Ltd",
        "asset_class": "equity",
        "sector": "Technology",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.150,
        "annual_volatility": 0.23,
        "equity_corr": 0.68,
    },
    {
        "ticker": "ICICIBANK.NS",
        "name": "ICICI Bank Ltd",
        "asset_class": "equity",
        "sector": "Finance",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.170,
        "annual_volatility": 0.22,
        "equity_corr": 0.81,
    },
    {
        "ticker": "HINDUNILVR.NS",
        "name": "Hindustan Unilever Ltd",
        "asset_class": "equity",
        "sector": "Consumer",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.115,
        "annual_volatility": 0.16,
        "equity_corr": 0.52,
    },
    {
        "ticker": "WIPRO.NS",
        "name": "Wipro Ltd",
        "asset_class": "equity",
        "sector": "Technology",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.120,
        "annual_volatility": 0.24,
        "equity_corr": 0.62,
    },
    {
        "ticker": "SUNPHARMA.NS",
        "name": "Sun Pharmaceutical Industries Ltd",
        "asset_class": "equity",
        "sector": "Healthcare",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.155,
        "annual_volatility": 0.18,
        "equity_corr": 0.45,
    },
    {
        "ticker": "MARUTI.NS",
        "name": "Maruti Suzuki India Ltd",
        "asset_class": "equity",
        "sector": "Consumer",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.140,
        "annual_volatility": 0.21,
        "equity_corr": 0.66,
    },
    {
        "ticker": "DRREDDY.NS",
        "name": "Dr. Reddy's Laboratories Ltd",
        "asset_class": "equity",
        "sector": "Healthcare",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.130,
        "annual_volatility": 0.19,
        "equity_corr": 0.42,
    },
    {
        "ticker": "TATAMOTORS.NS",
        "name": "Tata Motors Ltd",
        "asset_class": "equity",
        "sector": "Consumer",
        "category": "indian_equity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.185,
        "annual_volatility": 0.31,
        "equity_corr": 0.71,
    },
    # ── Global ETFs ───────────────────────────────────────────────────────────
    {
        "ticker": "SPY",
        "name": "SPDR S&P 500 ETF Trust",
        "asset_class": "equity",
        "sector": "US Market",
        "category": "global_etf",
        "currency": "USD",
        "is_synthetic": False,
        "annual_return": 0.125,
        "annual_volatility": 0.17,
        "equity_corr": 0.40,
    },
    {
        "ticker": "QQQ",
        "name": "Invesco QQQ Trust (NASDAQ 100)",
        "asset_class": "equity",
        "sector": "US Market",
        "category": "global_etf",
        "currency": "USD",
        "is_synthetic": False,
        "annual_return": 0.160,
        "annual_volatility": 0.22,
        "equity_corr": 0.44,
    },
    {
        "ticker": "EEM",
        "name": "iShares MSCI Emerging Markets ETF",
        "asset_class": "equity",
        "sector": "International",
        "category": "global_etf",
        "currency": "USD",
        "is_synthetic": False,
        "annual_return": 0.085,
        "annual_volatility": 0.19,
        "equity_corr": 0.58,
    },
    # ── Commodities & Crypto ──────────────────────────────────────────────────
    {
        "ticker": "GOLDBEES.NS",
        "name": "Nippon India ETF Gold BeES",
        "asset_class": "commodity",
        "sector": "Precious Metals",
        "category": "commodity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.110,
        "annual_volatility": 0.14,
        "equity_corr": 0.05,
    },
    {
        "ticker": "SILVERBEES.NS",
        "name": "Nippon India ETF Silver BeES",
        "asset_class": "commodity",
        "sector": "Precious Metals",
        "category": "commodity",
        "currency": "INR",
        "is_synthetic": False,
        "annual_return": 0.130,
        "annual_volatility": 0.25,
        "equity_corr": 0.15,
    },
    {
        "ticker": "BTC-USD",
        "name": "Bitcoin USD",
        "asset_class": "alternative",
        "sector": "Digital Assets",
        "category": "crypto",
        "currency": "USD",
        "is_synthetic": False,
        "annual_return": 0.350,
        "annual_volatility": 0.65,
        "equity_corr": 0.22,
    },
    # ── Deterministic Modeled Assets (Synthetic) ──────────────────────────────
    {
        "ticker": "SBI_FD",
        "name": "State Bank of India Fixed Deposit (1-Year)",
        "asset_class": "debt",
        "sector": "Fixed Income",
        "category": "synthetic",
        "currency": "INR",
        "is_synthetic": True,
        "annual_return": 0.070,
        "annual_volatility": 0.001,
        "equity_corr": 0.0,
        "assumption_notes": "Modeled with constant daily compounding yield accrual at 7.0% p.a.",
    },
    {
        "ticker": "HDFC_FD",
        "name": "HDFC Bank Fixed Deposit (1-Year)",
        "asset_class": "debt",
        "sector": "Fixed Income",
        "category": "synthetic",
        "currency": "INR",
        "is_synthetic": True,
        "annual_return": 0.071,
        "annual_volatility": 0.001,
        "equity_corr": 0.0,
        "assumption_notes": "Modeled with constant daily compounding yield accrual at 7.1% p.a.",
    },
    {
        "ticker": "INDIA_GOVT_10Y",
        "name": "Government of India 10-Year Benchmark Bond",
        "asset_class": "debt",
        "sector": "Fixed Income",
        "category": "synthetic",
        "currency": "INR",
        "is_synthetic": True,
        "annual_return": 0.072,
        "annual_volatility": 0.035,
        "equity_corr": -0.12,
        "assumption_notes": "Deterministic yield model at 7.2% with modified duration ~6.8 sensitivity.",
    },
    {
        "ticker": "INDIA_CORP_AAA",
        "name": "CRISIL AAA Rated Corporate Bond Benchmark",
        "asset_class": "debt",
        "sector": "Fixed Income",
        "category": "synthetic",
        "currency": "INR",
        "is_synthetic": True,
        "annual_return": 0.080,
        "annual_volatility": 0.040,
        "equity_corr": -0.08,
        "assumption_notes": "Yield benchmark modeled at 8.0% p.a. with duration ~4.2.",
    },
    {
        "ticker": "EMBASSY_REIT",
        "name": "Embassy Office Parks REIT",
        "asset_class": "alternative",
        "sector": "Real Estate",
        "category": "synthetic",
        "currency": "INR",
        "is_synthetic": True,
        "annual_return": 0.085,
        "annual_volatility": 0.140,
        "equity_corr": 0.42,
        "assumption_notes": "Model based on regular distribution yield plus long-term NAV growth.",
    },
]
