"""Decision brief and critic validation schemas."""

from typing import Literal, Optional

from pydantic import BaseModel, Field

ConfidenceLevel = Literal["low", "medium", "high"]


class Claim(BaseModel):
    """An individual assertion with traceable evidence citations."""

    text: str = Field(..., description="Sentence or assertion made in the brief")
    evidence_ids: list[str] = Field(
        ..., min_length=1, description="List of cited evidence IDs (e.g. ['E1', 'E4'])"
    )


class ConfidenceRating(BaseModel):
    """Confidence assessment with underlying rationale."""

    level: ConfidenceLevel
    reason: str


class DecisionBrief(BaseModel):
    """Synthesized, multi-agent evaluation brief for Decision Studio."""

    summary: str = Field(..., description="Executive summary of the candidate asset's impact")
    candidate_ticker: str = Field(..., description="Evaluated ticker symbol")
    bull_case: list[str] = Field(..., description="Key supported arguments favoring allocation")
    bear_case: list[str] = Field(..., description="Key supported arguments advising caution")
    currency_view: Optional[str] = Field(
        default=None, description="FX risk and INR exposure analysis"
    )
    sentiment_view: Optional[str] = Field(
        default=None, description="Recent news and market sentiment summary"
    )
    regime_view: Optional[str] = Field(
        default=None, description="Macroeconomic and market regime context"
    )
    risks: list[str] = Field(..., description="Identified portfolio and market risks")
    what_would_change_this: list[str] = Field(
        ..., description="Catalysts or conditions that would flip the thesis"
    )
    confidence: ConfidenceRating = Field(
        ..., description="Overall confidence level with justification"
    )
    claims: list[Claim] = Field(..., description="All factual claims tied to explicit evidence IDs")
    disclaimer: str = Field(
        default="This analysis is for educational and decision-support purposes only and does not constitute investment advice.",
        description="Mandatory legal disclaimer",
    )


class CriticIssue(BaseModel):
    """Specific flaw detected by the Critic agent."""

    severity: Literal["error", "warning"]
    claim_text: Optional[str] = None
    issue_type: Literal[
        "missing_citation",
        "invalid_evidence_id",
        "numeric_mismatch",
        "directive_language",
        "logical_contradiction",
        "unsupported_claim",
    ]
    message: str


class CriticReview(BaseModel):
    """Validation report generated by the Critic agent."""

    verdict: Literal["approved", "needs_revision", "rejected"]
    groundedness_score: float = Field(
        ..., ge=0.0, le=1.0, description="Proportion of verified claims"
    )
    issues: list[CriticIssue] = Field(default_factory=list)
    revision_count: int = Field(default=0)
